[package]
name = "rustlox"
version = "0.1.0"
authors = ["kyle.coffey <kyle.coffey@tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "^0.5"
eyre = "^0.6"
enum-map = "^0.6"
lazy_static = "^1.1"
